// Compat shim: legacy `@/lib/tauri` import path now re-exports from the Electrobun IPC client.
// `isTauri()` always returns true since the renderer always runs inside Electrobun.
export const isTauri = (): boolean => true;
export {
  appendHistory,
  cancelQuery,
  checkForUpdate,
  connectToDatabase,
  deleteRedisKey,
  disconnectFromDatabase,
  ENGINE_SUPPORTS_ANALYZE,
  ENGINE_SUPPORTS_EXPLAIN,
  executeQuery,
  explainQuery,
  formatSql,
  getAllHistory,
  getConfig,
  getConnections,
  getHistory,
  getSchema,
  getServerVersion,
  getTabs,
  getUpdateChannel,
  installUpdate,
  isMacOS,
  listDatabases,
  onMenuNavigate,
  onUpdateProgress,
  openExternal,
  redisDbInfo,
  saveConfig,
  saveConnections,
  saveTabs,
  scanRedisKeys,
  setUpdateChannel,
  testConnection,
} from "@/lib/ipc";
export type {
  AppConfig,
  AvailableUpdate,
  ColumnDetail,
  ColumnInfo,
  ConnectionParams,
  DatabaseConnection,
  DocumentResult,
  ExecuteResult,
  ExplainEngine,
  ExplainParams,
  ExplainResult,
  ForeignKeyItem,
  HistoryEntry,
  HistoryFilters,
  IndexItem,
  PersistedTab,
  PlanCost,
  PlanNode,
  PlanRows,
  PlanTiming,
  QueryParams,
  QueryResult,
  RedisDbInfo,
  RedisKey,
  RedisKeyKind,
  RedisScanPage,
  RedisSizeUnit,
  SchemaInfo,
  SchemaItem,
  TableItem,
  TabState,
  TabularResult,
  TestConnectionResult,
  UpdateChannel,
  ViewItem,
} from "@/lib/ipc";
