[package]
name = "oh-my-query-drivers-redis"
version = "0.0.10"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
oh-my-query-core = { path = "../oh-my-query-core", features = ["redis-errors"] }
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
chrono.workspace = true
log.workspace = true
redis = { version = "0.27", features = ["tokio-comp", "aio"] }
urlencoding = "2"
