[package]
name = "oh-my-query-drivers-mssql"
version = "0.0.10"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
oh-my-query-core = { path = "../oh-my-query-core", features = ["mssql-errors"] }
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
chrono.workspace = true
log.workspace = true
futures.workspace = true
tiberius = { version = "0.12", default-features = false, features = [
  "tds73",
  "native-tls",
  "chrono",
] }
bb8 = "0.8"
bb8-tiberius = "0.15"
tokio-util = { version = "0.7", features = ["compat"] }
base64 = "0.22"
