[package]
name = "oh-my-query"
version = "0.0.9"
description = "A query UI tool"
authors = ["victor"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.83.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.4", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.10.0", features = ["devtools", "macos-private-api"] }
tauri-plugin-log = "2"
sqlx = { version = "0.8", features = [
  "runtime-tokio",
  "tls-native-tls",
  "postgres",
  "mysql",
  "sqlite",
] }
futures = "0.3"
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
urlencoding = "2"
mongodb = "3"
redis = { version = "0.27", features = ["tokio-comp", "aio"] }
dirs = "6"
polyglot-sql = "0.1"
reqwest = { version = "0.12", features = ["json", "native-tls"] }
