[package]
name = "oh-my-query-drivers-duckdb"
version = "0.0.10"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
oh-my-query-core = { path = "../oh-my-query-core", features = [
  "duckdb-errors",
] }
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
chrono.workspace = true
log.workspace = true
duckdb = { version = "1", features = ["bundled"] }
base64 = "0.22"
